export default ALL_TOWNS = [
  {
    id: "1",
    name: "Moving On",
    bio: "A place for finding peace and starting fresh.",
    activeFolks: 84,
    totalFolks: "1.3k",
  },
  {
    id: "2",
    name: "Quiet Reflections",
    bio: "For those who prefer introspection and calm conversations.",
    activeFolks: 45,
    totalFolks: "798",
  },
  {
    id: "3",
    name: "Second Chances",
    bio: "Discussing the complexities of getting back together.",
    activeFolks: 62,
    totalFolks: "1.03k",
  },
  {
    id: "4",
    name: "Fresh Starts",
    bio: "Starting over and navigating a new life post-breakup.",
    activeFolks: 107,
    totalFolks: "1.4k",
  },
  {
    id: "5",
    name: "Unsent Letters",
    bio: "Share what you never got to say.",
    activeFolks: 39,
    totalFolks: "652",
  },
  {
    id: "6",
    name: "Ghosted",
    bio: "For those who were left with no explanation.",
    activeFolks: 77,
    totalFolks: "923",
  },
  {
    id: "7",
    name: "New Horizons",
    bio: "Looking ahead and focusing on personal growth.",
    activeFolks: 91,
    totalFolks: "1.1k",
  },
  {
    id: "8",
    name: "The Talk",
    bio: "Rehashing the dreaded breakup conversations.",
    activeFolks: 59,
    totalFolks: "856",
  },
  {
    id: "9",
    name: "Closure Club",
    bio: "Find closure and share your experiences.",
    activeFolks: 68,
    totalFolks: "1k",
  },
  {
    id: "10",
    name: "Healing Steps",
    bio: "Focused on healing and moving forward.",
    activeFolks: 120,
    totalFolks: "2.4k",
  },
];
